### PR TITLE
task-8: containerization

### PR DESCRIPTION
**Pull request by AnaBelochka**
Link to updated apiPath.ts

- https://github.com/AnaBelochka/shop-react-redux-cloudfront/blob/main/src/constants/apiPaths.ts

What was done:

 - Dockerfile was prepared, image is building. Image size was minimized to be less than 500 MB.
 - Dockerfile was optimized. Files that change more often and commands that depend on them is included later, files and commands that change less is at the top.
 - Folders were added to .dockerignore, with explanations.
 -  Elastic Beanstalk application was initialized.
 - Environment was created and the app was deployed to the AWS cloud. 
 - FE application was updated with Cart API endpoint.

### CODE REVIEW

**Comment by mtpYa** [comment]
Can you please check cart API link http://anabelochka-cart-api-dev.eu-west-1.elasticbeanstalk.com. It does not work.

**Comment by AnaBelochka** [comment]
> Can you please check cart API link http://anabelochka-cart-api-dev.eu-west-1.elasticbeanstalk.com. It does not work.

Hi! Yes, sorry for that. Now it works!

**Comment by xdMus** [comment]
Hey. Please revise your evaluation. Everything works properly, you made a mistake 
image

**Comment by AnaBelochka** [comment]
> Hey. Please revise your evaluation. Everything works properly, you made a mistake image

changed

**Pull request merged**
